# Generated by Django 4.0.3 on 2022-03-13 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contact_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': 'Форма связи', 'verbose_name_plural': 'Формы связи'},
        ),
    ]
