# Generated by Django 4.0.3 on 2022-03-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_brand_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Группа брендов'},
        ),
        migrations.AddField(
            model_name='product',
            name='Availability',
            field=models.CharField(choices=[('В наличии', 'В наличии'), ('Нет наличии', 'Нет в наличии')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название бренда'),
        ),
    ]
