# Generated by Django 4.0.3 on 2022-03-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_brand_options_product_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Availability',
            field=models.CharField(choices=[('В наличии', 'В наличии'), ('Нет наличии', 'Нет в наличии')], max_length=100, null=True, verbose_name='Наличие товара'),
        ),
    ]
